### ISSUE TITLE
PYTHONPATH causing issues

### ISSUE THREAD

**Issue by harmon** [brainsik/virtualenv-burrito#70] opened 2016-05-31 18:53 UTC
Hi!

I love the burrito! It's the tastiest! Thanks for all your hard work.

When you use this library, it sets this environment variable in your shell:

```
PYTHONPATH=~/.venvburrito/lib/python2.7/site-packages
```

Since the `six` lib is already in there, when I try and use a virtual environment and install six, it stays it's already satisfied. But my test environment doesn't load Virtualenv-Burrito, so it complains about six not being installed.

I had to `unset PYTHONPATH` and then run pip install.

Is there another strategy this library can employ instead of setting PYTHONPATH to get things loading?

Regards,
Adam

**Comment by brainsik** [comment] 2016-05-31 22:02
Ay, there’s the rub! Since we aren't installing to a system location (virtualenv-burrito lives in the user's home) we won't be found via `sys.path`. The only way I know to get noticed is to set `PYTHONPATH`, which has unfortunate consequences; see #55.

There may be something we could do with `/usr/local`, but that starts getting dicey with regard to permissions and how the system is configured. So, basically, I haven't had a chance to figure out how to get around this. It's definitely on my radar, though.

Going to close this as a duplicate of #55. Feel free to continue the discussion, though. I'm open to suggestions.

Thanks for your time.

**Closed by brainsik** 2016-05-31 22:02 UTC
